spring:
    datasource:
        name: syg
        url: jdbc:mysql://localhost:3306/base-boot?characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    redis:
        host: localhost
        password: root
        port: 6379
        timeout: 300
mybatis:
    mapperLocations: classpath:mappers/*.xml
    type-handlers-package: cn.wscq.name.domain.dao.mybatis
    type-aliases-package: cn.wscq.name.domain.model.mybatis
pagehelper:
    helper-dialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    rowBoundsWithCount: true
server:
    port: 2333
    context-path: '/'
flyway:
  baseline-on-migrate: true
