language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
services:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS base-boot;'
  - redis-server --port 6379 --requirepass 'root'